#!/bin/bash
cd /home/pi
cp /home/pi/Langstone/Langstone_Lime.conf /tmp
cp /home/pi/Langstone/Langstone_Pluto.conf /tmp
rm -rf /home/pi/Langstone
git clone http://www.github.com/g4eml/Langstone
/home/pi/Langstone/build
cp /tmp/Langstone_Lime.conf /home/pi/Langstone
cp /tmp/Langstone_Pluto.conf /home/pi/Langstone
chmod +x /home/pi/Langstone/build
chmod +x /home/pi/Langstone/run_lime
chmod +x /home/pi/Langstone/stop_lime
chmod +x /home/pi/Langstone/run_pluto
chmod +x /home/pi/Langstone/stop_pluto
chmod +x /home/pi/Langstone/update
chmod +x /home/pi/Langstone/update-dev
chmod +x /home/pi/Langstone/set_pluto
chmod +x /home/pi/Langstone/set_sdr
chmod +x /home/pi/Langstone/set_sound

/home/pi/Langstone/set_sdr


